// Generated by Corda Narration Pipeline
export type Beat = {
  id: string;
  start: number; // in seconds
  end: number;   // in seconds
  duration: number; // in seconds
  title: string;
  text: string;
};

export const TOTAL_DURATION_SECONDS = 82.85;
export const FPS = 30;
export const TOTAL_DURATION_FRAMES = Math.ceil(TOTAL_DURATION_SECONDS * FPS);

export const beats: Beat[] = [
  {
    "id": "BEAT_01",
    "title": "BEAT_01: The Privacy Question",
    "start": 0.0,
    "end": 11.91,
    "duration": 11.91,
    "text": "Every developer asks the same question: when open-source AI frameworks claim to be private, do their public codebases actually keep that promise?"
  },
  {
    "id": "BEAT_02",
    "title": "BEAT_02: The Contradiction Exposed",
    "start": 11.91,
    "end": 28.15,
    "duration": 16.24,
    "text": "Take this framework: documentation boldly claims \"Self-hosted, 100% private, no telemetry.\" But inspect the actual code. Active PostHog imports, API keys initialized, and telemetry capture events firing on task dispatch."
  },
  {
    "id": "BEAT_03",
    "title": "BEAT_03: Corda Console Ingestion",
    "start": 28.15,
    "end": 39.52,
    "duration": 11.37,
    "text": "That is where Corda steps in. By supplying the target repository code and public privacy policy directly into the Corda console..."
  },
  {
    "id": "BEAT_04",
    "title": "BEAT_04: GenLayer Comparative Consensus Pipeline",
    "start": 39.52,
    "end": 52.52,
    "duration": 13.0,
    "text": "...Corda triggers an Intelligent Contract on GenLayer. Non-deterministic web nodes independently crawl the documentation and code manifests, running comparative semantic evaluation across decentralized validators."
  },
  {
    "id": "BEAT_05",
    "title": "BEAT_05: The Finalized Verdict",
    "start": 52.52,
    "end": 64.43,
    "duration": 11.91,
    "text": "The multi-validator consensus is finalized: Disclosure Mismatch. Corda extracts the exact contradiction, detailing the active analytics SDKs against the unfulfilled marketing promise."
  },
  {
    "id": "BEAT_06",
    "title": "BEAT_06: Tamper-Evident On-Chain Proof",
    "start": 64.43,
    "end": 79.05,
    "duration": 14.62,
    "text": "Every report is immutably committed to GenLayer Studionet with GenVM Result: Success. Contract zero x seven zero c two, finalized across independent validators with public transaction proofs."
  },
  {
    "id": "BEAT_07",
    "title": "BEAT_07: Closing Anthem",
    "start": 79.05,
    "end": 82.85,
    "duration": 3.8,
    "text": "Claims are easy. Evidence is harder. Corda."
  }
];
